"""
Artifacts: Structured data models for the Planner-Executor-Critic (P-E-C) flow.

This module contains Pydantic models for the MVP P-E-C pipeline:
- PlanResult: output from Planner (structured plan with steps)
- StepResult: output from Executor (result of executing one step)
- CriticResult: output from Critic (verdict on step quality)

These artifacts are:
- Generated by components in the pipeline
- Validated through Pydantic (type safety, constraints)
- Serialized into RunContext events and persisted to SQLite

Architecture Note:
When additional flows are implemented (e.g. ReAct, Hub-and-Spoke, Reflection),
they should add their own module (e.g. flows/react/models.py) with flow-specific artifacts.
This keeps the codebase explicit: each flow owns its artifact definitions.
The universal abstraction across flows is RunContext.events, not shared Step models.
"""

from flows.pec.models import (
    PlanResult,
    PlanStep,
    StepResult,
    CriticResult,
    CriticIssue,
)

__all__ = [
    "PlanResult",
    "PlanStep",
    "StepResult",
    "CriticResult",
    "CriticIssue",
]
